### ISSUE TITLE
operate_valve_states.py

### ISSUE THREAD

**Issue by johodges** [johodges/mbzirc_c2_auto#22]
@vtalats I updated operate_valve_states.py in my local copy such that the classes are changed as shown below.

class MoveToValve(smach.State):
    """Move to the valve to prepare for video servo

    Outcomes
    --------
        atValve : at the valve ready to servo in

    """

    def __init__(self):
        smach.State.__init__(self,
                             outcomes=['atValve',
                                       'moveStuck',
                                       'moveFailed'],
                             input_keys=['move_counter_in'],
                             output_keys=['move_counter_out'])

    def execute(self, userdata):
        max_retries = 5

        valve_ID = rospy.get_param('valve_ID')
        valve = rospy.get_param('valve')
 
        valve_ID_ready_pos = np.empty([3])
        valve_ID_ready_pos[0] = valve[0]-0.4
        valve_ID_ready_pos[1] = valve[1]+valve_ID[1]
        valve_ID_ready_pos[2] = valve[2]+valve_ID[2]

        rospy.set_param('ee_position', [float(valve_ID_ready_pos[0]),
                                        float(valve_ID_ready_pos[1]),
                                        float(valve_ID_ready_pos[2])])

        prc = subprocess.Popen("rosrun mbzirc_grasping move_arm_param.py", shell=True)
        prc.wait()

        move_state = rospy.get_param('move_arm_status')

        # Preset the out move counter to 0, override if necessary
        userdata.move_counter_out = 0

        if move_state == 'success':
            return 'atValve'

        else:
            if userdata.move_counter_in < max_retries:
                userdata.move_counter_out = userdata.move_counter_in + 1
                return 'moveStuck'

            else:
                return 'moveFailed'

**Comment by vtalats** [comment]
Added in Pull Request #24
