### ISSUE TITLE
arm_nav_correct catkin_make can't find manipulator_msgs

### ISSUE THREAD

**Issue by johodges** [johodges/mbzirc_c2_auto#5]
All,

I tried to build arm_nav_correct with catkin_make but I get the error that it cannot find manipulator_msgs. I did "sudo apt-get install ros-indigo-manipulator-msgs" and it was already installed. When I do "roscd manipulator_msgs" it finds the package. Any ideas?

Thanks,

Jonathan

**Comment by vtalats** [comment]
@luandoan @johodges This failed for me too.  Is there an additional package we should be installing Luan?

**Comment by vtalats** [comment]
@johodges would you please review the changes and make sure that you can now build the package?  If all works you can close this issue.

**Comment by johodges** [comment]
@vtalats Compiles correctly. Merged the branch and closing this issue.
